spring:
  datasource:
    url: jdbc:postgresql://dpg-d80paa50lvsc738u5e9g-a.frankfurt-postgres.render.com:5432/alumnos_icva
    username: root
    password: BiQqpwPe9QneEB3ueE95Na3xsL37sMg5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false